name: Deploy to Firebase
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Save Build
        uses: actions/upload-artifact@master
        with:
          name: vpx-js
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone VPWeb
        run: git clone https://github.com/freezy/vpweb.git .
      - name: Install Dependencies
        run: npm ci
      - name: Clean VPX-JS
        run: rm -rf node_modules/vpx-js/dist
      - name: Download VPX-JS Build
        uses: actions/download-artifact@master
        with:
          name: vpx-js
          path: node_modules/vpx-js/dist
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
